spring.application.name=SecureQRCodeGenerator
spring.datasource.url=jdbc:mysql://ballast.proxy.rlwy.net:52702/railway
spring.datasource.username=root
spring.datasource.password=GSrgANisxyQtNEGWEwgdytVagoKKVylK
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show_sql= true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
server.port=8080