spring.application.name=SecureQRCodeGenerator
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/secure_qr_db
spring.datasource.username=root
spring.datasource.password=Rexlord2020$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show_sql= true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
server.port=8080